### ISSUE TITLE
Tatum - questions

### ISSUE THREAD

**Issue by Smrecz** [curraprotocol/tatum-extension#1]
Hello, want to bring couple points to your attention:

1. ETHEREUM_GOERLI was decommissioned and support has ended 12/2023 - would be best to not include it in the list of supported chains as it will be eventually removed from the SDK and replaced by HOLESKY
2.  Please consider passing only the Curra api key as plugin configuration and instantiating instance inside the plugin's init(), this will allow Tatum SDK to manage plugin lifecycle (leveraging init() and destroy())

**Comment by affixpin** [comment]
Included changes regarding your recommendations in the commit 9c714b2
If it's okay – let's close the issue, thank you for your feedback

**Comment by Smrecz** [comment]
@poloplayingsolo LGTM, pls adjust readme to accomodate the changes as well

**Comment by affixpin** [comment]
> @poloplayingsolo LGTM, pls adjust readme to accomodate the changes as well

oh, sorry, missed that, updated in e2a5264

**Comment by Smrecz** [comment]
Splendid, much appreciate!
